# require: rubocop-performance
AllCops:
  Excludes:
    - db/schema.rb

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
